### ISSUE TITLE
About changing styles

### ISSUE THREAD

**Issue by ChrisCreatorArcade** [mvanlonden/grommet-css#1]
I'm a bit new to using this and grommet, how do I go about creating a custom style after forking?

**Comment by mvanlonden** [comment]
Hi @ChrisCreatorArcade you should be able to do this by looking at some of the existing styles like [vanilla](https://github.com/grommet/grommet/tree/c76789b00fdcf3443735feb2bfacc1a5a70d9994/src/scss/vanilla). If you have scss built into your project you can just create a theme scss file and import it. Make sure that file imports grommet core.

If you don't have scss built into your project you can fork this repo, create your style, run the build command and include your fork as a npm dep on your main project.

**Comment by mvanlonden** [comment]
Will post an example shortly

**Comment by mvanlonden** [comment]
Checkout the [buildabode theme](https://github.com/mvanlonden/grommet-css/tree/master/themes/buildabode). Be sure to add your theme to the npm script and import it in your application from the build folder.
